# NumPy



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [253]:
import numpy as np
print(np.__version__)

1.19.5




---



## 배열 생성

### 리스트로 배열 만들기


In [254]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 2 3 4 5]


In [255]:
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 9


In [256]:
a3 = np.array([ [ [1,2,3], [4,5,6] ],
               [ [7, 8, 9], [10, 11, 12] ],
               [ [13, 14, 15], [16, 17, 18]]])
print(a3)
print(a3[0,1,1])
print(a3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
5
(3, 2, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [257]:
a4 = np.zeros(10)
print(a4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


* `ones()`: 모든 요소를 1로 초기화

In [258]:
a5 = np.ones(10)
print(a5)
print('\n')
a6 = np.ones((3, 4)) #행,렬
print(a6)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


* `full()`: 모든 요소를 지정한 값으로 초기화

In [259]:
a7 = np.full((3,3), 3.14)
print(a7)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [260]:
a8 = np.eye(3) #단위 행렬 = 곱해도 같은 값이 나옴.
print(a8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


* `tri()`: 삼각행렬 생성

In [261]:
a9 = np.tri(3) #삼각 행렬
print(a9)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [262]:
b1 = np.empty(10) #초기화 하지 않은 배열 생성 - 기존 메모리 위치에 존재하는 값이 있음.
print(b1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [263]:
b2 = np.zeros_like(a3) #shape따기
print(b2)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [264]:
b3 = np.ones_like(a3) #shape따고 1 넣기
print(b3)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [265]:
b4 = np.full_like(a3, 10) #shape따고 입력값 풀로.
print(b4)

[[[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]]


### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [266]:
b5 = np.arange(0, 30, 2) #정수 범위로 배열 생성
print(b5)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [267]:
b6 = np.linspace(0, 1, 5) #범위 내에서 균등 간격의 배열 생성
print(b6)

[0.   0.25 0.5  0.75 1.  ]


* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [268]:
b7 = np.logspace(0.1, 1, 20)
print(b7)

[ 1.25892541  1.40400425  1.565802    1.74624535  1.94748304  2.1719114
  2.42220294  2.70133812  3.0126409   3.35981829  3.74700446  4.17881006
  4.66037703  5.19743987  5.79639395  6.46437163  7.2093272   8.04013161
  8.9666781  10.        ]


### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [269]:
b8 = np.random.random((3, 3))
print(b8)

[[0.34098829 0.69405477 0.10224841]
 [0.81349399 0.59803257 0.83913946]
 [0.32688203 0.43039388 0.03973888]]


* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [270]:
b9 = np.random.randint(0, 10, (3, 3)) #Int형.
print(b9)

[[1 3 6]
 [6 2 2]
 [6 7 5]]


* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [271]:
c1 = np.random.normal(0, 1, (3, 3)) #정규분포를 고려함. (평균:0, 표편:1, 3x3배열)
print(c1)

[[ 0.63046133  0.78451455 -0.35751494]
 [-1.4566161   0.93300371  0.14452071]
 [ 1.06651806 -1.18910049  0.59940713]]


* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [272]:
c2 = np.random.rand(3, 3)
print(c2)

[[0.24717797 0.30661629 0.58197795]
 [0.77645781 0.00842951 0.98334363]
 [0.31536337 0.84474797 0.94137393]]


* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [273]:
c3 = np.random.randn(3, 3)
print(c3)

[[-0.27133265  1.43020304 -0.30582488]
 [-0.49204401  0.16474146 -0.59626027]
 [-0.74510354  0.0409171   0.298056  ]]


### 표준 데이터 타입

In [274]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [275]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [276]:
np.full((3, 3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [277]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [278]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [279]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [280]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [281]:
def array_info(array):
    print(array)
    print("ndim(차원):", array.ndim) #차원
    print("shape(모양):", array.shape) #모양
    print("dtype(데이터타입):", array.dtype) #데이터 타입
    print("size(수량):", array.size) #사이즈 ("수량")
    print("itemsize(아이템사이즈):", array.itemsize) #각 하나의 아이템이 갖는 크기 (바이트)
    print("nbytes(전체사이즈):", array.nbytes) #전체 바이트 (아이템 사이즈 x 수량)
    print("strides(다음으로의 사이즈):", array.strides) #다음(차원)으로 넘어가기 위해 필요한 사이즈. ex) a[1]에서 a[2]로 넘어가려면 int기준 8바이트가 필요하다.

In [282]:
array_info(a1) #1차원 배열

[4 2 3 4 5]
ndim(차원): 1
shape(모양): (5,)
dtype(데이터타입): int64
size(수량): 5
itemsize(아이템사이즈): 8
nbytes(전체사이즈): 40
strides(다음으로의 사이즈): (8,)


In [283]:
array_info(a2) #2차원

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim(차원): 2
shape(모양): (3, 3)
dtype(데이터타입): int64
size(수량): 9
itemsize(아이템사이즈): 8
nbytes(전체사이즈): 72
strides(다음으로의 사이즈): (24, 8)


In [284]:
array_info(a3) #3차원

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
ndim(차원): 3
shape(모양): (3, 2, 3)
dtype(데이터타입): int64
size(수량): 18
itemsize(아이템사이즈): 8
nbytes(전체사이즈): 144
strides(다음으로의 사이즈): (48, 24, 8)


### 인덱싱(Indexing)

In [285]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 2 3 4 5]
4
3
5
4


In [286]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, 1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [287]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[1, 1, 0])
print(a3[1, -1, -1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
1
11
10
12


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [288]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1]) #reverse

[4 2 3 4 5]
[4 2]
[4 2 3 4 5]
[4]
[4 3 5]
[5 4 3 2 4]


In [289]:
print(a2)
print("----")
print(a2[1])
print("----")
print(a2[1 ,:])
print("----")
print(a2[:2, :3])
print("----")
print(a2[1, ::-1])
print("----")
print(a2[::-1, ::-1]) #fully reverse

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----
[4 5 6]
----
[4 5 6]
----
[[1 2 3]
 [4 5 6]]
----
[6 5 4]
----
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [290]:
print(a1)
print("----")
bi = [False, True, True, False, True]
print(a1[bi])
print("----")
bi = [True, False, True, True, False]
print(a1[bi])

[4 2 3 4 5]
----
[2 3 5]
----
[4 3 4]


In [291]:
print(a2)
print("----")
bi = np.random.randint(0, 2, (3,3), dtype=bool)
print(bi)
print("----")
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----
[[False  True  True]
 [False  True False]
 [False  True  True]]
----
[2 3 5 8 9]


### 팬시 인덱싱(Fancy Indedxing)

In [292]:
print(a1)
print([a1[0], a1[2]])
ind = [0, 2]
print(a1[ind])

ind = np.array([[0, 1], #중요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
               [2, 0]])
print("------")
print(a1[ind])

[4 2 3 4 5]
[4, 3]
[4 3]
------
[[4 2]
 [3 4]]


In [293]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])

print('--------')
print(a2[row, col]) # -> a2[0,1] a2[2,2]와 동일.
print('--------')
print(a2[row, :])
print('--------')
print(a2[:, col])
print('--------')
print(a2[row, 1])
print('--------')
print(a2[2, col])
print('--------')
print(a2[row, 1:])
print('--------')
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------
[2 9]
--------
[[1 2 3]
 [7 8 9]]
--------
[[2 3]
 [5 6]
 [8 9]]
--------
[2 8]
--------
[8 9]
--------
[[2 3]
 [8 9]]
--------
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [294]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 2 3 4 5]
[10  4  2  3  4  5]
[ 4  2 10  3  4  5]


In [295]:
print(a2)
print("--")
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
print("--")
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
--
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [296]:
print(a1)
a1[0] = 3
a1[1] = 2
a1[2] = 1
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[4 2 3 4 5]
[3 2 1 4 5]
[9 2 1 4 5]
[9 0 1 0 0]
[9 4 1 4 4]


In [297]:
print(a2)
print('--')
a2[0, 0] = 3
a2[1, 1] = 2
a2[2, 2] = 1
a2[0] = 4
print(a2)
print('---')
a2[1:, 2] = 9
print(a2)
print('---')
row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--
[[4 4 4]
 [4 2 6]
 [7 8 1]]
---
[[4 4 4]
 [4 2 9]
 [7 8 9]]
---
[[4 0 4]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [298]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 1 4 4]
[9 1 4 4]
[9 4 1 4 4]


In [299]:
print(a2)
print('---')
b2 = np.delete(a2, 1, axis=0)
print(b2)
print('---')
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[4 0 4]
 [4 2 0]
 [7 8 9]]
---
[[4 0 4]
 [7 8 9]]
---
[[4 4]
 [4 0]
 [7 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [300]:
print(a2)
print('---')
print(a2[:2, :2])
print('---')
a2_sub = a2[:2, :2]
print(a2_sub)
print('---')
a2_sub[:, 1] = 0
print(a2_sub) #복사본이 아니므로, 바로 적용됨. (동일한 메모리 위치이기 때문이다.)
print('---')
print(a2)

[[4 0 4]
 [4 2 0]
 [7 8 9]]
---
[[4 0]
 [4 2]]
---
[[4 0]
 [4 2]]
---
[[4 0]
 [4 0]]
---
[[4 0 4]
 [4 0 0]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [301]:
print(a2)
a2_sub_copy = a2[:2, :2].copy() #명시적으로 복사 함. (서로 다른 메모리 위치에 수정하는 것.)
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[4 0 4]
 [4 0 0]
 [7 8 9]]
[[4 0]
 [4 0]]
[[4 1]
 [4 1]]
[[4 0 4]
 [4 0 0]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [302]:
print(a2)
print(a2.T)

[[4 0 4]
 [4 0 0]
 [7 8 9]]
[[4 4 7]
 [0 0 8]
 [4 0 9]]


In [303]:
print(a3)
print('---')
print(a3.T)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
---
[[[ 1  7 13]
  [ 4 10 16]]

 [[ 2  8 14]
  [ 5 11 17]]

 [[ 3  9 15]
  [ 6 12 18]]]


In [304]:
print(a2)
print(a2.swapaxes(1, 0))

[[4 0 4]
 [4 0 0]
 [7 8 9]]
[[4 4 7]
 [0 0 8]
 [4 0 9]]


In [305]:
print(a3)
print('---')
print(a3.swapaxes(0, 1))
print('---')
print(a3.swapaxes(1, 2))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
---
[[[ 1  2  3]
  [ 7  8  9]
  [13 14 15]]

 [[ 4  5  6]
  [10 11 12]
  [16 17 18]]]
---
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]

 [[13 16]
  [14 17]
  [15 18]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [306]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3)) #1차원 -> 2차원 배열

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [307]:
print(n1)
print(n1[np.newaxis, :5]) #newaxis의 위치에 따라 행, 열이 됨.
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [308]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
print('---')
n2.resize((5, 2))
print(n2)

[[5 9 3 8 7]
 [3 9 4 4 6]]
---
[[5 9]
 [3 8]
 [7 3]
 [9 4]
 [4 6]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [309]:
n2.resize((5, 5))
print(n2)

[[5 9 3 8 7]
 [3 9 4 4 6]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [310]:
n2.resize((3, 3))
print(n2)

[[5 9 3]
 [8 7 3]
 [9 4 4]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [311]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('---')
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [312]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [313]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [314]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [315]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [316]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [317]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a2, a2]) #기본 axis = 0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [318]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [319]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [320]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [321]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [322]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [323]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [324]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print('---')
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [325]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print('---')
b2, c2 = np.hsplit(a2, [2])
print(b2)
print('---')
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[1 2]
 [4 5]
 [7 8]]
---
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [326]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
print('---')
b2, c2 = np.dsplit(a3, [2])
print(b2)
print('---')
print(c2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
---
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
---
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [327]:
a1 = np.array([1, 2, 3])
print(a1)
print('---')
print(a1 + 5)
print('---')

a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('---')
print(a1 + a2) #브로드캐스팅

print('---')
b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)
print('---')
print(a1 + b2) #브로드캐스팅

[1 2 3]
---
[6 7 8]
---
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
---
[[1]
 [2]
 [3]]
---
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [328]:
a1 = np.arange(1, 10)
print(a1)
print(a1 + 1)
print('---')

print(np.add(a1, 10)) #덧셈
print('---')
print(a1-2)
print('---')
print(np.subtract(a1, 10)) #뺄셈
print('---')
print(-a1)
print('---')
print(np.negative(a1)) #단항 음수
print('---')
print(a1 * 2)
print('---')
print(np.multiply(a1, 2)) #곱하기
print('---')
print(a1 / 2) #
print('---')
print(np.divide(a1, 2)) #나누기
print('---')
print(a1 // 2)
print('---')
print(np.floor_divide(a1, 2)) #나누기 내림
print('---')
print(a1 ** 2) 
print('---')
print(np.power(a1, 2)) #제곱
print('---')
print(a1 % 2)
print('---')
print(np.mod(a1, 2)) #나머지

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
---
[11 12 13 14 15 16 17 18 19]
---
[-1  0  1  2  3  4  5  6  7]
---
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
---
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
---
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
---
[ 2  4  6  8 10 12 14 16 18]
---
[ 2  4  6  8 10 12 14 16 18]
---
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
---
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
---
[0 1 1 2 2 3 3 4 4]
---
[0 1 1 2 2 3 3 4 4]
---
[ 1  4  9 16 25 36 49 64 81]
---
[ 1  4  9 16 25 36 49 64 81]
---
[1 0 1 0 1 0 1 0 1]
---
[1 0 1 0 1 0 1 0 1]


In [329]:
a1 = np.arange(1, 10)
print(a1)
print('---')

b1 = np.random.randint(1, 10, size=9)
print(a1 + b1)
print('---')
print(a1 - b1)
print('---')
print(a1 * b1)
print('---')
print(a1 / b1)
print('---')
print(a1 // b1)
print('---')
print(a1 ** b1)
print('---')
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
---
[ 6  9  7 11  6 14 15 14 16]
---
[-4 -5 -1 -3  4 -2 -1  2  2]
---
[ 5 14 12 28  5 48 56 48 63]
---
[0.2        0.28571429 0.75       0.57142857 5.         0.75
 0.875      1.33333333 1.28571429]
---
[0 0 0 0 5 0 0 1 1]
---
[      1     128      81   16384       5 1679616 5764801  262144 4782969]
---
[1 2 3 4 0 6 7 2 2]


In [330]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('---')
b2= np.random.randint(1, 10, size=(3, 3))
print(b2)
print('---')
print(a2 + b2)
print('---')
print(a2 - b2)
print('---')
print(a2 * b2)
print('---')
print(a2 / b2)
print('---')
print(a2 // b2)
print('---')
print(a2 ** b2)
print('---')
print(a2% b2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[6 5 6]
 [8 2 2]
 [4 2 7]]
---
[[ 7  7  9]
 [12  7  8]
 [11 10 16]]
---
[[-5 -3 -3]
 [-4  3  4]
 [ 3  6  2]]
---
[[ 6 10 18]
 [32 10 12]
 [28 16 63]]
---
[[0.16666667 0.4        0.5       ]
 [0.5        2.5        3.        ]
 [1.75       4.         1.28571429]]
---
[[0 0 0]
 [0 2 3]
 [1 4 1]]
---
[[      1      32     729]
 [  65536      25      36]
 [   2401      64 4782969]]
---
[[1 2 3]
 [4 1 0]
 [3 0 2]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [331]:
a1 = np.random.randint(-10, 0, size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1)) #abs(solute)

[ -8 -10  -5 -10  -6]
[ 8 10  5 10  6]
[ 8 10  5 10  6]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [332]:
a1 = np.random.randint(1, 11, size=5)
print(a1)
print(np.square(a1)) #제곱
print(np.sqrt(a1)) #제곱근

[ 6  4 10  9  6]
[ 36  16 100  81  36]
[2.44948974 2.         3.16227766 3.         2.44948974]


#### 지수와 로그 함수 (Exponential and Log Function)

In [333]:
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1)) #자연상수 e에 대한 지수
print(np.exp2(a1)) #2에 대한 지수
print(np.power(a1, 2)) #제곱

[5 9 6 3 5]
[ 148.4131591  8103.08392758  403.42879349   20.08553692  148.4131591 ]
[ 32. 512.  64.   8.  32.]
[25 81 36  9 25]


In [334]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[5 9 6 3 5]
[1.60943791 2.19722458 1.79175947 1.09861229 1.60943791]
[2.32192809 3.169925   2.5849625  1.5849625  2.32192809]
[0.69897    0.95424251 0.77815125 0.47712125 0.69897   ]


#### 삼각 함수(Trigonometrical Function)


In [335]:
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))


[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [336]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))


[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [337]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
38 38
[ 8 15 15] [ 8 15 15]
[21  9  8] [21  9  8]


#### cumsum(): 누적합 계산

In [338]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
[ 5 14 21 22 25 30 32 35 38]
[[ 5  9  7]
 [ 6 12 12]
 [ 8 15 15]]
[[ 5 14 21]
 [ 1  4  9]
 [ 2  5  8]]


#### diff(): 차분 계산

In [339]:
print(a2)
print('---')
print(np.diff(a2))
print('---')
print(np.diff(a2, axis=0))
print('---')
print(np.diff(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
---
[[ 4 -2]
 [ 2  2]
 [ 1  0]]
---
[[-4 -6 -2]
 [ 1  0 -2]]
---
[[ 4 -2]
 [ 2  2]
 [ 1  0]]


#### prod(): 곱 계산

In [340]:
print(a2)
print('---')
print(np.prod(a2))
print('---')
print(np.prod(a2, axis=0))
print('---')
print(np.prod(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
---
85050
---
[ 10  81 105]
---
[315  15  18]


#### cumprod(): 누적곱 계산

In [341]:
print(a2)
print('---')
print(np.cumprod(a2))
print('---')
print(np.cumprod(a2, axis=0))
print('---')
print(np.cumprod(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
---
[    5    45   315   315   945  4725  9450 28350 85050]
---
[[  5   9   7]
 [  5  27  35]
 [ 10  81 105]]
---
[[  5  45 315]
 [  1   3  15]
 [  2   6  18]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [342]:
print(a2)
print('---')
b2 = np.ones_like(a2)
print(b2)
print('---')
print(np.dot(a2, b2))
print('---')
print(np.matmul(a2, b2))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
---
[[1 1 1]
 [1 1 1]
 [1 1 1]]
---
[[21 21 21]
 [ 9  9  9]
 [ 8  8  8]]
---
[[21 21 21]
 [ 9  9  9]
 [ 8  8  8]]


#### tensordot(): 텐서곱 계산

In [343]:
print(a2)
print('---')
print(b2)
print('---')
print(np.tensordot(a2, b2))
print('---')
print(np.tensordot(a2, b2, axes=0))
print('---')
print(np.tensordot(a2, b2, axes=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
---
[[1 1 1]
 [1 1 1]
 [1 1 1]]
---
38
---
[[[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]]
---
[[21 21 21]
 [ 9  9  9]
 [ 8  8  8]]


#### cross(): 벡터곱

In [344]:
x = [1, 2, 3]
y = [4, 5 ,6]
print(np.cross(x, y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [345]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[21 21 21]
 [ 9  9  9]
 [ 8  8  8]]
[[5 5 5 5 5 5 5 5 5]
 [9 9 9 9 9 9 9 9 9]
 [7 7 7 7 7 7 7 7 7]
 [1 1 1 1 1 1 1 1 1]
 [3 3 3 3 3 3 3 3 3]
 [5 5 5 5 5 5 5 5 5]
 [2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3]]


#### mean(): 평균 계산

In [346]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
4.222222222222222
[2.66666667 5.         5.        ]
[7.         3.         2.66666667]


#### std(): 표준 편차 계산

In [347]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
1
[1 3 3]
[5 1 2]


#### var(): 분산 계산

In [348]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
5.728395061728396
[2.88888889 8.         2.66666667]
[2.66666667 2.66666667 0.22222222]


#### min(): 최소값

In [349]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
1
[1 3 3]
[5 1 2]


#### max(): 최대값

In [350]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
9
[5 9 7]
[9 5 3]


#### argmin(): 최소값 인덱스

In [351]:
print(a2)
print(np.argmin(a2)) #위치 값을 출력함.
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
3
[1 1 2]
[0 0 0]


#### argmax(): 최대값 인덱스

In [352]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
1
[0 0 0]
[1 2 1]


#### median(): 중앙값

In [353]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[5 9 7]
 [1 3 5]
 [2 3 3]]
3.0
[2. 3. 5.]
[7. 3. 3.]


#### percentile(): 백분위 수



In [354]:
a1 = np.array([0, 1, 2, 3]) #영상 1:52:00 보기!!
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [355]:
a2 = np.array([[False, False, False],
              [False, True, True],
              [False, True, True]])
print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [356]:
a2 = np.array([[False, False, True],
              [True, True, True],
              [False, True, True]])
print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)


In [357]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [358]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('---')
print(np.sum(a2))
print('---')
print(np.count_nonzero(a2 > 5)) #5이상인거의 0이 아닌 것의 개수.
print('---')
print(np.sum(a2 > 5)) #조건을 만족하는 개수.
print('---')
print(np.sum(a2 > 5, axis=0))
print('---')
print(np.sum(a2 > 5, axis=1))
print('---')
print(np.any(a2 > 5)) #하나라도 만족?
print('---')
print(np.any(a2 > 5, axis=0))
print('---')
print(np.any(a2 > 5, axis=1))
print('---')
print(np.all(a2 > 5)) #모두가 만족?
print('---')
print(np.all(a2 > 5, axis=0))
print('---')
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
45
---
4
---
4
---
[1 1 2]
---
[0 1 3]
---
True
---
[ True  True  True]
---
[False  True  True]
---
False
---
[False False False]
---
[False False  True]


In [359]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [360]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF]) #nan:숫자가 아님, inf:무한, NINF:음의 무한
print(a1)
print(np.isnan(a1)) #숫자가 아닌 것
print(np.isinf(a1)) #무한
print(np.isfinite(a1)) #유한

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [361]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('---')
print((a2 > 5) & (a2 < 8))
print('---')
print(a2[(a2 > 5) & (a2 < 8)])
print('---')
print((a2 > 5) | (a2 < 8))
print('---')
print(a2[(a2 > 5) | (a2 < 8)])
print('---')
print((a2 > 5) ^ (a2 < 8))
print('---')
print(a2[(a2 > 5) ^ (a2 < 8)])
print('---')
print(~(a2 > 5))
print('---')
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[False False False]
 [False False  True]
 [ True False False]]
---
[6 7]
---
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
---
[1 2 3 4 5 6 7 8 9]
---
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
---
[1 2 3 4 5 8 9]
---
[[ True  True  True]
 [ True  True False]
 [False False False]]
---
[1 2 3 4 5]


### 배열 정렬

In [362]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1)) #정렬
print(a1) #원본 유지
print(np.argsort(a1)) #~번째가 n번 위치에 와야 한다.
print(a1.sort()) #원본을 정렬함.
print(a1)

[3 6 9 5 6 7 3 8 2 2]
[2 2 3 3 5 6 6 7 8 9]
[3 6 9 5 6 7 3 8 2 2]
[8 9 0 6 3 1 4 5 7 2]
None
[2 2 3 3 5 6 6 7 8 9]


In [363]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[3 2 8]
 [1 4 5]
 [9 3 1]]
[[1 2 1]
 [3 3 5]
 [9 4 8]]
[[2 3 8]
 [1 4 5]
 [1 3 9]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [364]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print('--')
print(np.partition(a1, 3))


[3 4 6 8 4 9 9 4 3 4]
--
[4 3 3 4 4 9 9 8 6 4]


In [365]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print('---')
print(np.partition(a2, 3))
print('---')
print(np.partition(a2, 3, axis=0))
print('---')
print(np.partition(a2, 3, axis=1))

[[1 3 7 5 5]
 [4 1 2 4 3]
 [5 8 8 4 8]
 [4 3 4 2 9]
 [1 1 2 5 1]]
---
[[3 1 5 5 7]
 [1 2 3 4 4]
 [4 5 8 8 8]
 [2 4 3 4 9]
 [1 1 1 2 5]]
---
[[1 1 4 2 3]
 [1 1 2 4 1]
 [4 3 2 4 5]
 [4 3 7 5 8]
 [5 8 8 5 9]]
---
[[3 1 5 5 7]
 [1 2 3 4 4]
 [4 5 8 8 8]
 [2 4 3 4 9]
 [1 1 1 2 5]]


## 배열 입출력


In [367]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
np.save("a", a2)

[[3 9 6 2 4]
 [2 2 7 9 2]
 [4 3 3 9 7]
 [1 4 6 9 4]
 [4 1 9 7 6]]


In [369]:
!ls

a.npy                  numpy_study_file.ipynb


In [371]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez("ab", a2, b2)

[[6 7 2 2 6]
 [5 8 7 4 4]
 [9 4 7 7 7]
 [5 8 2 7 9]
 [6 6 8 9 3]]


In [372]:
!ls

a.npy                  ab.npz                 numpy_study_file.ipynb


In [373]:
npy = np.load("a.npy")
print(npy)

[[3 9 6 2 4]
 [2 2 7 9 2]
 [4 3 3 9 7]
 [1 4 6 9 4]
 [4 1 9 7 6]]


In [383]:
npz = np.load("ab.npz")
print(npz.files)
print(npz['arr_0'])
print('---')
print(npz['arr_1'])

['arr_0', 'arr_1']
[[3 9 6 2 4]
 [2 2 7 9 2]
 [4 3 3 9 7]
 [1 4 6 9 4]
 [4 1 9 7 6]]
---
[[6 7 2 2 6]
 [5 8 7 4 4]
 [9 4 7 7 7]
 [5 8 2 7 9]
 [6 6 8 9 3]]


In [384]:
print(a2)
np.savetxt("a.csv", a2, delimiter=',') #delimiter = 구분자

[[3 9 6 2 4]
 [2 2 7 9 2]
 [4 3 3 9 7]
 [1 4 6 9 4]
 [4 1 9 7 6]]


In [385]:
!ls

a.csv                  ab.npz
a.npy                  numpy_study_file.ipynb


In [386]:
!cat a.csv

3.000000000000000000e+00,9.000000000000000000e+00,6.000000000000000000e+00,2.000000000000000000e+00,4.000000000000000000e+00
2.000000000000000000e+00,2.000000000000000000e+00,7.000000000000000000e+00,9.000000000000000000e+00,2.000000000000000000e+00
4.000000000000000000e+00,3.000000000000000000e+00,3.000000000000000000e+00,9.000000000000000000e+00,7.000000000000000000e+00
1.000000000000000000e+00,4.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00,4.000000000000000000e+00
4.000000000000000000e+00,1.000000000000000000e+00,9.000000000000000000e+00,7.000000000000000000e+00,6.000000000000000000e+00


In [387]:
csv = np.loadtxt("a.csv", delimiter=',')
print(csv)

[[3. 9. 6. 2. 4.]
 [2. 2. 7. 9. 2.]
 [4. 3. 3. 9. 7.]
 [1. 4. 6. 9. 4.]
 [4. 1. 9. 7. 6.]]


In [388]:
print(b2)
np.savetxt("b.csv", b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5') #fmt='%.2e' = 소수점 둘째 자리

[[6 7 2 2 6]
 [5 8 7 4 4]
 [9 4 7 7 7]
 [5 8 2 7 9]
 [6 6 8 9 3]]


In [389]:
!cat b.csv

# c1, c2, c3, c4, c5
6.00e+00,7.00e+00,2.00e+00,2.00e+00,6.00e+00
5.00e+00,8.00e+00,7.00e+00,4.00e+00,4.00e+00
9.00e+00,4.00e+00,7.00e+00,7.00e+00,7.00e+00
5.00e+00,8.00e+00,2.00e+00,7.00e+00,9.00e+00
6.00e+00,6.00e+00,8.00e+00,9.00e+00,3.00e+00


In [390]:
csv = np.loadtxt('b.csv', delimiter=',')
print(csv)

[[6. 7. 2. 2. 6.]
 [5. 8. 7. 4. 4.]
 [9. 4. 7. 7. 7.]
 [5. 8. 2. 7. 9.]
 [6. 6. 8. 9. 3.]]




---

