In [1]:
import numpy as np
print(np.__version__)

a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
print(a1)

a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[2, 2])

a3 = np.array([ [ [1,2,3], [4,5,6] ],
               [ [7, 8, 9], [10, 11, 12] ] ])
print(a3)
print(a3[0,0,1])
print(a3.shape)

a4 = np.zeros(10)
print(a4)

a5 = np.ones(10)
print(a5)

a6 = np.ones((3, 3))
print(a6)

a7 = np.full((3,3), 3.14)
print(a7)

a8 = np.eye(3) #단위 행렬
print(a8)

a9 = np.tri(3) #삼각 행렬
print(a9)

b1 = np.empty(10) #초기화 하지 않은 배열 생성 - 기존 메모리 위치에 존재하는 값이 있음.
print(b1)

b2 = np.zeros_like(a3) #shape따기
print(b2)

b3 = np.ones_like(a3) #shape따고 1 넣기
print(b3)

b4 = np.full_like(a3, 10) #shape따고 입력값 풀로.
print(b4)

#---------------

b5 = np.arange(0, 30, 2) #정수 범위로 배열 생성
print(b5)

b6 = np.linspace(0, 1, 5) #범위 내에서 균등 간격의 배열 생성
print(b6)

b7 = np.logspace(0.1, 1, 20)
print(b7)

#-------------

b8 = np.random.random((3, 3))
print(b8)

b9 = np.random.randint(0, 10, (3, 3))
print(b9)

c1 = np.random.normal(0, 1, (3, 3)) #정규분포를 고려함. (평균:0, 표편:1, 3x3배열)
print(c1)

c2 = np.random.rand(3, 3)
print(c2)

c3 = np.random.randn(3, 3)
print(c3)

1.19.2
[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 9
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2
(2, 2, 3)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[0.   0.25 0.5  0.75 1.  ]
[ 1.25892541  1.40400425  1.565802    1.74624535  1.94748304  2.1719114
  2.42220294  2.70133812  3.0126409   3.35981829  3.74700446  4.17881006
  4.66037703  5.19743987  5.79639395  6.46437163  7.2093272   8.04013161
  8.9666781  10.        ]
[[0.51695105 0.26133107 0.39413285]
 [0.10598472 0.18212714 0.05359374]
 [0.33335068 0.35599548 0.8