# NumPy




---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [836]:
import numpy as np
print(np.__version__)

1.19.5




---



## 배열 생성

### 리스트로 배열 만들기


In [837]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 2 3 4 5]


In [838]:
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 9


In [839]:
a3 = np.array([ [ [1,2,3], [4,5,6] ],
               [ [7, 8, 9], [10, 11, 12] ],
               [ [13, 14, 15], [16, 17, 18]]])
print(a3)
print(a3[0,1,1])
print(a3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
5
(3, 2, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [840]:
a4 = np.zeros(10)
print(a4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


* `ones()`: 모든 요소를 1로 초기화

In [841]:
a5 = np.ones(10)
print(a5)
print('\n')
a6 = np.ones((3, 4)) #행,렬
print(a6)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


* `full()`: 모든 요소를 지정한 값으로 초기화

In [842]:
a7 = np.full((3,3), 3.14)
print(a7)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [843]:
a8 = np.eye(3) #단위 행렬 = 곱해도 같은 값이 나옴.
print(a8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


* `tri()`: 삼각행렬 생성

In [844]:
a9 = np.tri(3) #삼각 행렬
print(a9)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [845]:
b1 = np.empty(10) #초기화 하지 않은 배열 생성 - 기존 메모리 위치에 존재하는 값이 있음.
print(b1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [846]:
b2 = np.zeros_like(a3) #shape따기
print(b2)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [847]:
b3 = np.ones_like(a3) #shape따고 1 넣기
print(b3)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [848]:
b4 = np.full_like(a3, 10) #shape따고 입력값 풀로.
print(b4)

[[[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]]


### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [849]:
b5 = np.arange(0, 30, 2) #정수 범위로 배열 생성
print(b5)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [850]:
b6 = np.linspace(0, 1, 5) #범위 내에서 균등 간격의 배열 생성
print(b6)

[0.   0.25 0.5  0.75 1.  ]


* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [851]:
b7 = np.logspace(0.1, 1, 20)
print(b7)

[ 1.25892541  1.40400425  1.565802    1.74624535  1.94748304  2.1719114
  2.42220294  2.70133812  3.0126409   3.35981829  3.74700446  4.17881006
  4.66037703  5.19743987  5.79639395  6.46437163  7.2093272   8.04013161
  8.9666781  10.        ]


### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [852]:
b8 = np.random.random((3, 3))
print(b8)

[[0.25500962 0.08546392 0.47705737]
 [0.90878704 0.40483143 0.47602294]
 [0.60617707 0.4514222  0.25019649]]


* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [853]:
b9 = np.random.randint(0, 10, (3, 3)) #Int형.
print(b9)

[[7 5 4]
 [2 3 9]
 [9 2 0]]


* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [854]:
c1 = np.random.normal(0, 1, (3, 3)) #정규분포를 고려함. (평균:0, 표편:1, 3x3배열)
print(c1)

[[ 0.159763    0.05719665 -0.49781273]
 [ 1.12790464 -0.63753276 -0.66280665]
 [ 1.40585341  0.45434491  0.1984975 ]]


* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [855]:
c2 = np.random.rand(3, 3)
print(c2)

[[0.72295856 0.10655761 0.41972754]
 [0.87448161 0.61423444 0.966962  ]
 [0.32198837 0.21461678 0.70212418]]


* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [856]:
c3 = np.random.randn(3, 3)
print(c3)

[[-0.65171321  0.12542696 -2.21592239]
 [-0.59729342 -0.29693894 -1.71804199]
 [-0.44673269 -0.19057637  0.02925823]]


### 표준 데이터 타입

In [857]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [858]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [859]:
np.full((3, 3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [860]:
date = np.array('2020-01-01', dtype=np.datetime64)
print(date)

2020-01-01


In [861]:
print(date + np.arange(12))

['2020-01-01' '2020-01-02' '2020-01-03' '2020-01-04' '2020-01-05'
 '2020-01-06' '2020-01-07' '2020-01-08' '2020-01-09' '2020-01-10'
 '2020-01-11' '2020-01-12']


In [862]:
datetime = np.datetime64('2020-06-01 12:00')
print(datetime)

2020-06-01T12:00


In [863]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns') #nano second
print(datetime)

2020-06-01T12:00:12.340000000




---



## 배열 조회

### 배열 속성 정보

In [864]:
def array_info(array):
    print(array)
    print("ndim(차원):", array.ndim) #차원
    print("shape(모양):", array.shape) #모양
    print("dtype(데이터타입):", array.dtype) #데이터 타입
    print("size(수량):", array.size) #사이즈 ("수량")
    print("itemsize(아이템사이즈):", array.itemsize) #각 하나의 아이템이 갖는 크기 (바이트)
    print("nbytes(전체사이즈):", array.nbytes) #전체 바이트 (아이템 사이즈 x 수량)
    print("strides(다음으로의 사이즈):", array.strides) #다음(차원)으로 넘어가기 위해 필요한 사이즈. ex) a[1]에서 a[2]로 넘어가려면 int기준 8바이트가 필요하다.

In [865]:
array_info(a1) #1차원 배열

[4 2 3 4 5]
ndim(차원): 1
shape(모양): (5,)
dtype(데이터타입): int64
size(수량): 5
itemsize(아이템사이즈): 8
nbytes(전체사이즈): 40
strides(다음으로의 사이즈): (8,)


In [866]:
array_info(a2) #2차원

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim(차원): 2
shape(모양): (3, 3)
dtype(데이터타입): int64
size(수량): 9
itemsize(아이템사이즈): 8
nbytes(전체사이즈): 72
strides(다음으로의 사이즈): (24, 8)


In [867]:
array_info(a3) #3차원

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
ndim(차원): 3
shape(모양): (3, 2, 3)
dtype(데이터타입): int64
size(수량): 18
itemsize(아이템사이즈): 8
nbytes(전체사이즈): 144
strides(다음으로의 사이즈): (48, 24, 8)


### 인덱싱(Indexing)

In [868]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 2 3 4 5]
4
3
5
4


In [869]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, 1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [870]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[1, 1, 0])
print(a3[1, -1, -1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
1
11
10
12


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [871]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1]) #reverse

[4 2 3 4 5]
[4 2]
[4 2 3 4 5]
[4]
[4 3 5]
[5 4 3 2 4]


In [872]:
print(a2)
print("----")
print(a2[1])
print("----")
print(a2[1 ,:])
print("----")
print(a2[:2, :3])
print("----")
print(a2[1, ::-1])
print("----")
print(a2[::-1, ::-1]) #fully reverse

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----
[4 5 6]
----
[4 5 6]
----
[[1 2 3]
 [4 5 6]]
----
[6 5 4]
----
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [873]:
print(a1)
print("----")
bi = [False, True, True, False, True]
print(a1[bi])
print("----")
bi = [True, False, True, True, False]
print(a1[bi])

[4 2 3 4 5]
----
[2 3 5]
----
[4 3 4]


In [874]:
print(a2)
print("----")
bi = np.random.randint(0, 2, (3,3), dtype=bool)
print(bi)
print("----")
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----
[[ True  True False]
 [False  True False]
 [ True  True False]]
----
[1 2 5 7 8]


### 팬시 인덱싱(Fancy Indedxing)

In [875]:
print(a1)
print([a1[0], a1[2]])
ind = [0, 2]
print(a1[ind])

ind = np.array([[0, 1], #중요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
               [2, 0]])
print("차원 : ",np.ndim(ind))
print("------")
print(a1[ind])

[4 2 3 4 5]
[4, 3]
[4 3]
차원 :  2
------
[[4 2]
 [3 4]]


In [876]:
print(a2)
row = np.array([0, 2]) #행
col = np.array([1, 2]) #열

print('--------')
print(a2[row, col]) # -> a2[0,1] a2[2,2]와 동일.
print('--------')
print(a2[row, :])
print('--------')
print(a2[:, col])
print('--------')
print(a2[row, 1])
print('--------')
print(a2[2, col])
print('--------')
print(a2[row, 1:])
print('--------')
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------
[2 9]
--------
[[1 2 3]
 [7 8 9]]
--------
[[2 3]
 [5 6]
 [8 9]]
--------
[2 8]
--------
[8 9]
--------
[[2 3]
 [8 9]]
--------
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [877]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1)

[4 2 3 4 5]
[10  4  2  3  4  5]
[ 4  2 10  3  4  5]


In [878]:
print(a2)
print("--")
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
print("--")
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
--
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [879]:
print(a1)
a1[0] = 3
a1[1] = 2
a1[2] = 1
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[4 2 3 4 5]
[3 2 1 4 5]
[9 2 1 4 5]
[9 0 1 0 0]
[9 4 1 4 4]


In [880]:
print(a2)
print('--')
a2[0, 0] = 3
a2[1, 1] = 2
a2[2, 2] = 1
a2[0] = 4
print(a2)
print('---')
a2[1:, 2] = 9
print(a2)
print('---')
row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--
[[4 4 4]
 [4 2 6]
 [7 8 1]]
---
[[4 4 4]
 [4 2 9]
 [7 8 9]]
---
[[4 0 4]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [881]:
print(a1)
b1 = np.delete(a1, 1) #non-touch original 'a1'
print(b1)
print(a1)

[9 4 1 4 4]
[9 1 4 4]
[9 4 1 4 4]


In [882]:
print(a2)
print('---')
b2 = np.delete(a2, 1, axis=0)
print(b2)
print('---')
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[4 0 4]
 [4 2 0]
 [7 8 9]]
---
[[4 0 4]
 [7 8 9]]
---
[[4 4]
 [4 0]
 [7 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [883]:
print(a2)
print('---')
print(a2[:2, :2])
print('---')
a2_sub = a2[:2, :2]
print(a2_sub)
print('---')
a2_sub[:, 1] = 0
print(a2_sub) #복사본이 아니므로, 바로 적용됨. (동일한 메모리 위치이기 때문이다.)
print('---')
print(a2)

[[4 0 4]
 [4 2 0]
 [7 8 9]]
---
[[4 0]
 [4 2]]
---
[[4 0]
 [4 2]]
---
[[4 0]
 [4 0]]
---
[[4 0 4]
 [4 0 0]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [884]:
print(a2)
a2_sub_copy = a2[:2, :2].copy() #명시적으로 복사 함. (서로 다른 메모리 위치에 수정하는 것.)
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[4 0 4]
 [4 0 0]
 [7 8 9]]
[[4 0]
 [4 0]]
[[4 1]
 [4 1]]
[[4 0 4]
 [4 0 0]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [885]:
print(a2)
print(a2.T)

[[4 0 4]
 [4 0 0]
 [7 8 9]]
[[4 4 7]
 [0 0 8]
 [4 0 9]]


In [886]:
print(a3)
print('---')
print(a3.T)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
---
[[[ 1  7 13]
  [ 4 10 16]]

 [[ 2  8 14]
  [ 5 11 17]]

 [[ 3  9 15]
  [ 6 12 18]]]


In [887]:
print(a2)
print(a2.swapaxes(1, 0))

[[4 0 4]
 [4 0 0]
 [7 8 9]]
[[4 4 7]
 [0 0 8]
 [4 0 9]]


In [888]:
print(a3)
print('---')
print(a3.swapaxes(0, 1))
print('---')
print(a3.swapaxes(1, 2))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
---
[[[ 1  2  3]
  [ 7  8  9]
  [13 14 15]]

 [[ 4  5  6]
  [10 11 12]
  [16 17 18]]]
---
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]

 [[13 16]
  [14 17]
  [15 18]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [889]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3)) #1차원 -> 2차원 배열

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [890]:
print(n1)
print(n1[np.newaxis, :5]) #newaxis의 위치에 따라 행, 열이 됨.
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [891]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
print('---')
n2.resize((5, 2))
print(n2)

[[2 3 2 1 4]
 [2 9 8 0 2]]
---
[[2 3]
 [2 1]
 [4 2]
 [9 8]
 [0 2]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [892]:
n2.resize((5, 5))
print(n2)

[[2 3 2 1 4]
 [2 9 8 0 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [893]:
n2.resize((3, 3))
print(n2)

[[2 3 2]
 [1 4 2]
 [9 8 0]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [894]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('---')
b2 = np.arange(10, 19).reshape(3, 3)
print(b2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [895]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [896]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [897]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [898]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [899]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [900]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a2, a2]) #기본 axis = 0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [901]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [902]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [903]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [904]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [905]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [906]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [907]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print('---')
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [908]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print('---')
b2, c2 = np.hsplit(a2, [2])
print(b2)
print('---')
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[1 2]
 [4 5]
 [7 8]]
---
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [909]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
print('---')
b2, c2 = np.dsplit(a3, [2])
print(b2)
print('---')
print(c2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
---
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
---
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [910]:
a1 = np.array([1, 2, 3])
print(a1)
print('---')
print(a1 + 5)
print('---')

a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('---')
print(a1 + a2) #브로드캐스팅

print('---')
b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)
print('---')
print(a1 + b2) #브로드캐스팅

[1 2 3]
---
[6 7 8]
---
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
---
[[1]
 [2]
 [3]]
---
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [911]:
a1 = np.arange(1, 10)
print(a1)

print(a1 + 1)
print('---')
print(np.add(a1, 10)) #덧셈
print('---')

print(a1 - 2)
print('---')
print(np.subtract(a1, 10)) #뺄셈
print('---')

print(-a1)
print('---')
print(np.negative(a1)) #단항 음수
print('---')

print(a1 * 2)
print('---')
print(np.multiply(a1, 2)) #곱하기
print('---')

print(a1 / 2)
print('---')
print(np.divide(a1, 2)) #나누기
print('---')

print(a1 // 2)
print('---')
print(np.floor_divide(a1, 2)) #나누기 내림
print('---')

print(a1 ** 2) 
print('---')
print(np.power(a1, 2)) #제곱
print('---')

print(a1 % 2)
print('---')
print(np.mod(a1, 2)) #나머지

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
---
[11 12 13 14 15 16 17 18 19]
---
[-1  0  1  2  3  4  5  6  7]
---
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
---
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
---
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
---
[ 2  4  6  8 10 12 14 16 18]
---
[ 2  4  6  8 10 12 14 16 18]
---
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
---
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
---
[0 1 1 2 2 3 3 4 4]
---
[0 1 1 2 2 3 3 4 4]
---
[ 1  4  9 16 25 36 49 64 81]
---
[ 1  4  9 16 25 36 49 64 81]
---
[1 0 1 0 1 0 1 0 1]
---
[1 0 1 0 1 0 1 0 1]


In [912]:
a1 = np.arange(1, 10)
print(a1)
print('---')

b1 = np.random.randint(1, 10, size=9)
print(a1 + b1)
print('---')
print(a1 - b1)
print('---')
print(a1 * b1)
print('---')
print(a1 / b1)
print('---')
print(a1 // b1)
print('---')
print(a1 ** b1)
print('---')
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
---
[ 3 10 12 13  9 13 12 14 11]
---
[-1 -6 -6 -5  1 -1  2  2  7]
---
[ 2 16 27 36 20 42 35 48 18]
---
[0.5        0.25       0.33333333 0.44444444 1.25       0.85714286
 1.4        1.33333333 4.5       ]
---
[0 0 0 0 1 0 1 1 4]
---
[     1    256  19683 262144    625 279936  16807 262144     81]
---
[1 2 3 4 1 6 2 2 1]


In [913]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('---')
b2= np.random.randint(1, 10, size=(3, 3))
print(b2)
print('---')
print(a2 + b2)
print('---')
print(a2 - b2)
print('---')
print(a2 * b2)
print('---')
print(a2 / b2)
print('---')
print(a2 // b2)
print('---')
print(a2 ** b2)
print('---')
print(a2 % b2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[1 1 6]
 [2 5 6]
 [9 1 7]]
---
[[ 2  3  9]
 [ 6 10 12]
 [16  9 16]]
---
[[ 0  1 -3]
 [ 2  0  0]
 [-2  7  2]]
---
[[ 1  2 18]
 [ 8 25 36]
 [63  8 63]]
---
[[1.         2.         0.5       ]
 [2.         1.         1.        ]
 [0.77777778 8.         1.28571429]]
---
[[1 2 0]
 [2 1 1]
 [0 8 1]]
---
[[       1        2      729]
 [      16     3125    46656]
 [40353607        8  4782969]]
---
[[0 0 3]
 [0 0 0]
 [7 0 2]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [914]:
a1 = np.random.randint(-10, 0, size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1)) #abs(solute)

[ -4  -7 -10  -8  -8]
[ 4  7 10  8  8]
[ 4  7 10  8  8]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [915]:
a1 = np.random.randint(1, 11, size=5)
print(a1)
print(np.square(a1)) #제곱
print(np.sqrt(a1)) #제곱근

[7 3 2 7 2]
[49  9  4 49  4]
[2.64575131 1.73205081 1.41421356 2.64575131 1.41421356]


#### 지수와 로그 함수 (Exponential and Log Function)

In [916]:
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1)) #자연상수 e에 대한 지수
print(np.exp2(a1)) #2에 대한 지수
print(np.power(a1, 2)) #제곱

[9 6 1 5 5]
[8.10308393e+03 4.03428793e+02 2.71828183e+00 1.48413159e+02
 1.48413159e+02]
[512.  64.   2.  32.  32.]
[81 36  1 25 25]


In [917]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[9 6 1 5 5]
[2.19722458 1.79175947 0.         1.60943791 1.60943791]
[3.169925   2.5849625  0.         2.32192809 2.32192809]
[0.95424251 0.77815125 0.         0.69897    0.69897   ]


#### 삼각 함수(Trigonometrical Function)


In [918]:
t = np.linspace(0, np.pi, 3)
print(np.pi)
print(t) # 0도, 90도, 180도(pi)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))


3.141592653589793
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [919]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))


[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [920]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
43 43
[21 10 12] [21 10 12]
[19 11 13] [19 11 13]


#### cumsum(): 누적합 계산

In [921]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
[ 9 16 19 24 26 30 37 38 43]
[[ 9  7  3]
 [14  9  7]
 [21 10 12]]
[[ 9 16 19]
 [ 5  7 11]
 [ 7  8 13]]


#### diff(): 차분 계산

In [922]:
print(a2)
print('---')
print(np.diff(a2))
print('---')
print(np.diff(a2, axis=0))
print('---')
print(np.diff(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
---
[[-2 -4]
 [-3  2]
 [-6  4]]
---
[[-4 -5  1]
 [ 2 -1  1]]
---
[[-2 -4]
 [-3  2]
 [-6  4]]


#### prod(): 곱 계산

In [923]:
print(a2)
print('---')
print(np.prod(a2))
print('---')
print(np.prod(a2, axis=0))
print('---')
print(np.prod(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
---
264600
---
[315  14  60]
---
[189  40  35]


#### cumprod(): 누적곱 계산

In [924]:
print(a2)
print('---')
print(np.cumprod(a2))
print('---')
print(np.cumprod(a2, axis=0))
print('---')
print(np.cumprod(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
---
[     9     63    189    945   1890   7560  52920  52920 264600]
---
[[  9   7   3]
 [ 45  14  12]
 [315  14  60]]
---
[[  9  63 189]
 [  5  10  40]
 [  7   7  35]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [925]:
print(a2)
print('---')
b2 = np.ones_like(a2)
print(b2)
print('---')
print(np.dot(a2, b2))
print('---')
print(np.matmul(a2, b2))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
---
[[1 1 1]
 [1 1 1]
 [1 1 1]]
---
[[19 19 19]
 [11 11 11]
 [13 13 13]]
---
[[19 19 19]
 [11 11 11]
 [13 13 13]]


#### tensordot(): 텐서곱 계산

In [926]:
print(a2)
print('---')
print(b2)
print('---')
print(np.tensordot(a2, b2))
print('---')
print(np.tensordot(a2, b2, axes=0))
print('---')
print(np.tensordot(a2, b2, axes=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
---
[[1 1 1]
 [1 1 1]
 [1 1 1]]
---
43
---
[[[[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]]
---
[[19 19 19]
 [11 11 11]
 [13 13 13]]


#### cross(): 벡터곱

In [927]:
x = [1, 2, 3]
y = [4, 5 ,6]
print(np.cross(x, y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [928]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[19 19 19]
 [11 11 11]
 [13 13 13]]
[[9 9 9 9 9 9 9 9 9]
 [7 7 7 7 7 7 7 7 7]
 [3 3 3 3 3 3 3 3 3]
 [5 5 5 5 5 5 5 5 5]
 [2 2 2 2 2 2 2 2 2]
 [4 4 4 4 4 4 4 4 4]
 [7 7 7 7 7 7 7 7 7]
 [1 1 1 1 1 1 1 1 1]
 [5 5 5 5 5 5 5 5 5]]


#### mean(): 평균 계산

In [929]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
4.777777777777778
[7.         3.33333333 4.        ]
[6.33333333 3.66666667 4.33333333]


#### std(): 표준 편차 계산

In [930]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
1
[5 1 3]
[3 2 1]


#### var(): 분산 계산

In [931]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
5.950617283950617
[2.66666667 6.88888889 0.66666667]
[6.22222222 1.55555556 6.22222222]


#### min(): 최소값

In [932]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
1
[5 1 3]
[3 2 1]


#### max(): 최대값

In [933]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
9
[9 7 5]
[9 5 7]


#### argmin(): 최소값 인덱스

In [934]:
print(a2)
print(np.argmin(a2)) #위치 값을 출력함.
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
7
[1 2 0]
[2 1 1]


#### argmax(): 최대값 인덱스

In [935]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
0
[0 0 2]
[0 0 0]


#### median(): 중앙값

In [936]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[9 7 3]
 [5 2 4]
 [7 1 5]]
5.0
[7. 2. 4.]
[7. 4. 5.]


#### percentile(): 백분위 수



In [937]:
a1 = np.array([0, 1, 2, 3]) #영상 1:52:00 보기!!
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [938]:
a2 = np.array([[False, False, False],
              [False, True, True],
              [False, True, True]])
print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [939]:
a2 = np.array([[False, False, True],
              [True, True, True],
              [False, True, True]])
print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)


In [940]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [941]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('---')
print(np.sum(a2))
print('---')
print(np.count_nonzero(a2 > 5)) #5이상인거의 0이 아닌 것의 개수.
print('---')
print(np.sum(a2 > 5)) #조건을 만족하는 개수.
print('---')
print(np.sum(a2 > 5, axis=0))
print('---')
print(np.sum(a2 > 5, axis=1))
print('---')
print(np.any(a2 > 5)) #하나라도 만족?
print('---')
print(np.any(a2 > 5, axis=0))
print('---')
print(np.any(a2 > 5, axis=1))
print('---')
print(np.all(a2 > 5)) #모두가 만족?
print('---')
print(np.all(a2 > 5, axis=0))
print('---')
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
45
---
4
---
4
---
[1 1 2]
---
[0 1 3]
---
True
---
[ True  True  True]
---
[False  True  True]
---
False
---
[False False False]
---
[False False  True]


In [942]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [943]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF]) #nan:숫자가 아님, inf:무한, NINF:음의 무한
print(a1)
print(np.isnan(a1)) #숫자가 아닌 것
print(np.isinf(a1)) #무한
print(np.isfinite(a1)) #유한

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [944]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print('---')
print((a2 > 5) & (a2 < 8))
print('---')
print(a2[(a2 > 5) & (a2 < 8)])
print('---')
print((a2 > 5) | (a2 < 8))
print('---')
print(a2[(a2 > 5) | (a2 < 8)])
print('---')
print((a2 > 5) ^ (a2 < 8))
print('---')
print(a2[(a2 > 5) ^ (a2 < 8)])
print('---')
print(~(a2 > 5))
print('---')
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[False False False]
 [False False  True]
 [ True False False]]
---
[6 7]
---
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
---
[1 2 3 4 5 6 7 8 9]
---
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
---
[1 2 3 4 5 8 9]
---
[[ True  True  True]
 [ True  True False]
 [False False False]]
---
[1 2 3 4 5]


### 배열 정렬

In [945]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1)) #정렬
print(a1) #원본 유지
print(np.argsort(a1)) #~번째가 n번 위치에 와야 한다.
print(a1.sort()) #원본을 정렬함.
print(a1)

[1 8 3 1 7 3 7 5 1 4]
[1 1 1 3 3 4 5 7 7 8]
[1 8 3 1 7 3 7 5 1 4]
[0 3 8 2 5 9 7 4 6 1]
None
[1 1 1 3 3 4 5 7 7 8]


In [946]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[2 7 5]
 [9 7 8]
 [1 3 5]]
[[1 3 5]
 [2 7 5]
 [9 7 8]]
[[2 5 7]
 [7 8 9]
 [1 3 5]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [947]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print('--')
print(np.partition(a1, 3))


[4 5 7 8 3 8 5 7 3 2]
--
[3 2 3 4 5 5 8 7 7 8]


In [948]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
print('---')
print(np.partition(a2, 3))
print('---')
print(np.partition(a2, 3, axis=0))
print('---')
print(np.partition(a2, 3, axis=1))

[[7 9 5 7 6]
 [1 1 9 3 4]
 [1 1 6 3 1]
 [3 2 8 2 5]
 [3 3 7 8 5]]
---
[[5 6 7 7 9]
 [3 1 1 4 9]
 [1 1 1 3 6]
 [2 3 2 5 8]
 [3 3 5 7 8]]
---
[[1 2 5 2 4]
 [1 1 6 3 1]
 [3 1 7 3 5]
 [3 3 8 7 5]
 [7 9 9 8 6]]
---
[[5 6 7 7 9]
 [3 1 1 4 9]
 [1 1 1 3 6]
 [2 3 2 5 8]
 [3 3 5 7 8]]


## 배열 입출력


In [949]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
np.save("a", a2)

[[6 4 8 8 3]
 [6 9 3 5 7]
 [8 6 7 5 1]
 [6 8 1 2 1]
 [5 7 9 3 5]]


In [950]:
!ls

a.csv                  ab.npz                 numpy_study_file.ipynb
a.npy                  b.csv


In [951]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez("ab", a2, b2)

[[9 7 5 7 3]
 [8 8 7 2 6]
 [7 8 3 6 3]
 [2 2 6 8 4]
 [9 9 1 1 9]]


In [952]:
!ls

a.csv                  ab.npz                 numpy_study_file.ipynb
a.npy                  b.csv


In [953]:
npy = np.load("a.npy")
print(npy)

[[6 4 8 8 3]
 [6 9 3 5 7]
 [8 6 7 5 1]
 [6 8 1 2 1]
 [5 7 9 3 5]]


In [954]:
npz = np.load("ab.npz")
print(npz.files)
print(npz['arr_0'])
print('---')
print(npz['arr_1'])

['arr_0', 'arr_1']
[[6 4 8 8 3]
 [6 9 3 5 7]
 [8 6 7 5 1]
 [6 8 1 2 1]
 [5 7 9 3 5]]
---
[[9 7 5 7 3]
 [8 8 7 2 6]
 [7 8 3 6 3]
 [2 2 6 8 4]
 [9 9 1 1 9]]


In [955]:
print(a2)
np.savetxt("a.csv", a2, delimiter=',') #delimiter = 구분자

[[6 4 8 8 3]
 [6 9 3 5 7]
 [8 6 7 5 1]
 [6 8 1 2 1]
 [5 7 9 3 5]]


In [956]:
!ls

a.csv                  ab.npz                 numpy_study_file.ipynb
a.npy                  b.csv


In [957]:
!cat a.csv

6.000000000000000000e+00,4.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00,3.000000000000000000e+00
6.000000000000000000e+00,9.000000000000000000e+00,3.000000000000000000e+00,5.000000000000000000e+00,7.000000000000000000e+00
8.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00,5.000000000000000000e+00,1.000000000000000000e+00
6.000000000000000000e+00,8.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,1.000000000000000000e+00
5.000000000000000000e+00,7.000000000000000000e+00,9.000000000000000000e+00,3.000000000000000000e+00,5.000000000000000000e+00


In [958]:
csv = np.loadtxt("a.csv", delimiter=',')
print(csv)

[[6. 4. 8. 8. 3.]
 [6. 9. 3. 5. 7.]
 [8. 6. 7. 5. 1.]
 [6. 8. 1. 2. 1.]
 [5. 7. 9. 3. 5.]]


In [959]:
print(b2)
np.savetxt("b.csv", b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5') #fmt='%.2e' = 소수점 둘째 자리

[[9 7 5 7 3]
 [8 8 7 2 6]
 [7 8 3 6 3]
 [2 2 6 8 4]
 [9 9 1 1 9]]


In [960]:
!cat b.csv

# c1, c2, c3, c4, c5
9.00e+00,7.00e+00,5.00e+00,7.00e+00,3.00e+00
8.00e+00,8.00e+00,7.00e+00,2.00e+00,6.00e+00
7.00e+00,8.00e+00,3.00e+00,6.00e+00,3.00e+00
2.00e+00,2.00e+00,6.00e+00,8.00e+00,4.00e+00
9.00e+00,9.00e+00,1.00e+00,1.00e+00,9.00e+00


In [961]:
csv = np.loadtxt('b.csv', delimiter=',')
print(csv)

[[9. 7. 5. 7. 3.]
 [8. 8. 7. 2. 6.]
 [7. 8. 3. 6. 3.]
 [2. 2. 6. 8. 4.]
 [9. 9. 1. 1. 9.]]




---

