# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [32]:
import numpy as np
print(np.__version__)

1.19.5




---



## 배열 생성

### 리스트로 배열 만들기


In [33]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 2 3 4 5]


In [34]:
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 9


In [35]:
a3 = np.array([ [ [1,2,3], [4,5,6] ],
               [ [7, 8, 9], [10, 11, 12] ] ])
print(a3)
print(a3[0,0,1])
print(a3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2
(2, 2, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [36]:
a4 = np.zeros(10)
print(a4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


* `ones()`: 모든 요소를 1로 초기화

In [37]:
a5 = np.ones(10)
print(a5)
print('\n')
a6 = np.ones((3, 3))
print(a6)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


* `full()`: 모든 요소를 지정한 값으로 초기화

In [38]:
a7 = np.full((3,3), 3.14)
print(a7)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [39]:
a8 = np.eye(3) #단위 행렬 = 곱해도 같은 값이 나옴.
print(a8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


* `tri()`: 삼각행렬 생성

In [40]:
a9 = np.tri(3) #삼각 행렬
print(a9)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [41]:
b1 = np.empty(10) #초기화 하지 않은 배열 생성 - 기존 메모리 위치에 존재하는 값이 있음.
print(b1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [42]:
b2 = np.zeros_like(a3) #shape따기
print(b2)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [43]:
b3 = np.ones_like(a3) #shape따고 1 넣기
print(b3)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [44]:
b4 = np.full_like(a3, 10) #shape따고 입력값 풀로.
print(b4)

[[[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]]


### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [45]:
b5 = np.arange(0, 30, 2) #정수 범위로 배열 생성
print(b5)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [46]:
b6 = np.linspace(0, 1, 5) #범위 내에서 균등 간격의 배열 생성
print(b6)

[0.   0.25 0.5  0.75 1.  ]


* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [47]:
b7 = np.logspace(0.1, 1, 20)
print(b7)

[ 1.25892541  1.40400425  1.565802    1.74624535  1.94748304  2.1719114
  2.42220294  2.70133812  3.0126409   3.35981829  3.74700446  4.17881006
  4.66037703  5.19743987  5.79639395  6.46437163  7.2093272   8.04013161
  8.9666781  10.        ]


### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [48]:
b8 = np.random.random((3, 3))
print(b8)

[[0.91951794 0.73908524 0.86837587]
 [0.47132821 0.77325706 0.3517372 ]
 [0.83148974 0.85690248 0.93703297]]


* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [49]:
b9 = np.random.randint(0, 10, (3, 3))
print(b9)

[[1 7 5]
 [1 6 3]
 [4 5 9]]


* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [50]:
c1 = np.random.normal(0, 1, (3, 3)) #정규분포를 고려함. (평균:0, 표편:1, 3x3배열)
print(c1)

[[ 0.08370058 -0.68165174 -0.19451447]
 [-0.08096246  0.50088106  0.55365716]
 [-1.98843265  1.18217055 -0.05560671]]


* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [51]:
c2 = np.random.rand(3, 3)
print(c2)

[[0.3574812  0.82419937 0.53806401]
 [0.07723469 0.93244529 0.82263254]
 [0.01477275 0.91536838 0.28351589]]


* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [52]:
c3 = np.random.randn(3, 3)
print(c3)

[[ 0.03692127  0.61860364 -0.14387635]
 [-1.92301755  0.31161379  0.23779579]
 [-0.83690162  0.34717167  0.45293639]]


### 표준 데이터 타입

In [53]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
np.ones((3, 3,), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [55]:
np.full((3, 3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [56]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [57]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [58]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [59]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [60]:
def array_info(array):
    print(array)
    print("ndim:", array.ndim) #차원
    print("shape:", array.shape)
    print("dtype:", array.dtype) #데이터 타입
    print("size:", array.size) #사이즈
    print("itemsize:", array.itemsize) #각 하나의 아이템이 갖는 크기 (바이트)
    print("nbytes:", array.nbytes) #전체 바이트 (아이템 사이즈 x 수량)
    print("strides", array.strides) #다음(차원)으로 넘어가기 위해 필요한 사이즈. ex) a[1]에서 a[2]로 넘어가려면 int기준 8바이트가 필요하다.

In [61]:
array_info(a1)

[4 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40
strides (8,)


In [62]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 8
nbytes: 72
strides (24, 8)


In [67]:
array_info(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
ndim: 3
shape: (2, 2, 3)
dtype: int64
size: 12
itemsize: 8
nbytes: 96
strides (48, 24, 8)


### 인덱싱(Indexing)

In [68]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 2 3 4 5]
4
3
5
4


In [69]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, 1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [73]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[1, 1, 0])
print(a3[1, -1, -1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
11
10
12


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [74]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1]) #reverse

[4 2 3 4 5]
[4 2]
[4 2 3 4 5]
[4]
[4 3 5]
[5 4 3 2 4]


In [75]:
print(a2)
print(a2[1])
print(a2[1 ,:])
print(a2[:2, :2])
print(a2[1, ::-1])
print(a2[::-1, ::-1]) #fully reverse

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[6 5 4]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [81]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])

bi = [True, False, True, True, False]
print(a1[bi])

[4 2 3 4 5]
[2 3 5]
[4 3 4]


In [99]:
print(a2)
bi = np.random.randint(0, 2, (3,3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True False  True]
 [ True  True False]
 [ True  True False]]
[1 3 4 5 7 8]


### 팬시 인덱싱(Fancy Indedxing)

In [103]:
print(a1)
print([a1[0], a1[2]])
ind = [0, 2]
print(a1[ind])

ind = np.array([[0, 1], #중요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
               [2, 0]])
print("------")
print(a1[ind])

[4 2 3 4 5]
[4, 3]
[4 3]
------
[[4 2]
 [3 4]]


In [110]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])

print('--------')
print(a2[row, col]) # -> a2[0,1] a2[2,2]와 동일.

print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [ ]:
44분!

### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님


* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사



---



## 배열 변환

### 배열 전치 및 축 변경

### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

* `newaxis()`: 새로운 축 추가

### 배열 크기 변경

* 배열 모양만 변경

* 배열 크기 증가
* 남은 공간은 0으로 채워짐

* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

### 배열 추가

* `append()`: 배열의 끝에 값 추가

* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

* `stack()`: 새로운 차원으로 연결

### 배열 분할

* `split()`: 배열 분할

* `vsplit()`: 수직 분할, 1차원으로 분할

* `hsplit()`: 수평 분할, 2차원으로 분할

* `dsplit()`: 깊이 분할, 3차원으로 분할



---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

### 산술 연산(Arithmetic Operators)

#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

#### 지수와 로그 함수 (Exponential and Log Function)

#### 삼각 함수(Trigonometrical Function)


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

#### cumsum(): 누적합 계산

#### diff(): 차분 계산

#### prod(): 곱 계산

#### cumprod(): 누적곱 계산

#### dot()/matmul(): 점곱/행렬곱 계산

#### tensordot(): 텐서곱 계산

#### cross(): 벡터곱

#### inner()/outer(): 내적/외적

#### mean(): 평균 계산

#### std(): 표준 편차 계산

#### var(): 분산 계산

#### min(): 최소값

#### max(): 최대값

#### argmin(): 최소값 인덱스

#### argmax(): 최대값 인덱스

#### median(): 중앙값

#### percentile(): 백분위 수



#### any()

#### all()

### 비교 연산(Comparison Operators)


#### 불리언 연산자(Boolean Operators)


### 배열 정렬

#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

## 배열 입출력


sample_data




---

